apiversion: v1 
kind: Service 
metadata:
  name: react-app 
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - port: 4000 
      protocol: TCP 
      targetPort: 4000 
      nodePort: 31000