# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: appointment-service
  namespace: default
  labels:
    app: appointment-service
spec:
  type: NodePort
  selector:
    app: appointment-service
  ports:
    - name: http
      port: 4000
      targetPort: 4000
      protocol: TCP
      nodePort: 31000  # 30000–32767 is valid; 31000 is fine
