apiVersion: v1 
kind: Service 
metadata:
  name: appointment-service
spec:
  type: NodePort
  selector:
    app: appointment-service
  ports:
    - port: 4000 
      protocol: TCP 
      targetPort: 4000 
      nodePort: 31000